# Generated by Django 4.2.7 on 2023-11-06 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hostel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostel_name', models.CharField(max_length=120)),
                ('category', models.CharField(choices=[('Single', 'Single'), ('Double', 'Double')], max_length=6)),
                ('price', models.DecimalField(decimal_places=2, max_digits=18)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, upload_to='images')),
                ('security', models.BooleanField(default=False)),
                ('shuttle', models.BooleanField(default=False)),
                ('reading_room', models.BooleanField(default=False)),
                ('wifi', models.BooleanField(default=False)),
                ('contact', models.CharField(max_length=20)),
                ('website', models.CharField(max_length=120)),
            ],
        ),
    ]
